#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
  aarch64)
    FLAKE_TARGET="aarch64-android"
    ;;
  *)
    echo -e "${RED}Unsupported architecture: $SYSTEM${NC}"
    exit 1
    ;;
esac

echo -e "${YELLOW}Starting...${NC}"

# We pass SSH from user to root so root can download secrets from our private Github

/run/current-system/sw/bin/nix build .#$FLAKE_TARGET $@

# removed the below because it was causing issues with the build (nix-on-droid has a different environment)
# sudo SSH_AUTH_SOCK=$SSH_AUTH_SOCK /run/current-system/sw/bin/nix build .#$FLAKE_TARGET $@ 

echo -e "${GREEN}Build complete!${NC}"
