#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
  aarch64)
    FLAKE_TARGET="aarch64-android"
    ;;
  *)
    echo -e "${RED}Unsupported architecture: $SYSTEM${NC}"
    exit 1
    ;;
esac

echo -e "${YELLOW}Starting...${NC}"

# Use nix directly since we're in the nix-on-droid environment
nix build .#$FLAKE_TARGET $@

echo -e "${GREEN}Build complete!${NC}"
