#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Starting...${NC}"

# Use nix-on-droid specific command
nix-on-droid switch .#

echo -e "${GREEN}Build complete!${NC}"
